import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { ReduxProvider } from "@/Redux/Provider";
import { AppProvider } from "@/context api/context";
import ErrorSuccessModal from "@/components/ErrorSuccessModal";
import DonateModal from "@/components/DonateModal";

export const metadata: Metadata = {
  title: "Febila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AppProvider>
            {children}
            <Sidebar />
            <DonateModal />
            <ErrorSuccessModal />
          </AppProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
